-- =============================================================================
-- Script: Migração Pendências v2
-- Descrição: Adiciona campos faltantes e ajusta a tabela para compatibilidade
-- Data: 2026-08-27
-- =============================================================================

-- Se a tabela já existe, dropar para recriar com todos os campos
DROP TABLE IF EXISTS pendencias CASCADE;

-- Criar tabela de pendências com TODOS os campos necessários
CREATE TABLE pendencias (
    -- Identificadores
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    materia_id BIGINT NOT NULL REFERENCES materia(id) ON DELETE CASCADE,
    avaliacao_id BIGINT REFERENCES avaliacao(id) ON DELETE CASCADE,

    -- Status de Pendências - MATÉRIAS
    status_criacao_avaliacao VARCHAR(20) CHECK (status_criacao_avaliacao IN ('PENDENTE', NULL)),
    status_plano_aula VARCHAR(20) CHECK (status_plano_aula IN ('PENDENTE', NULL)),
    status_plano_ensino VARCHAR(20) CHECK (status_plano_ensino IN ('PENDENTE', NULL)),

    -- Status de Pendências - AVALIAÇÕES
    status_avaliacao VARCHAR(20) CHECK (status_avaliacao IN ('PENDENTE', NULL)),
    status_gabarito VARCHAR(20) CHECK (status_gabarito IN ('PENDENTE', NULL)),
    status_revisao VARCHAR(20) CHECK (status_revisao IN ('PENDENTE', NULL)),
    status_cadastro_sgn VARCHAR(20) CHECK (status_cadastro_sgn IN ('PENDENTE', NULL)),
    acompanhamento_pedagogico_sgn VARCHAR(20) CHECK (acompanhamento_pedagogico_sgn IN ('PENDENTE', NULL)),

    -- Campos adicionais do formulário (usados por dashboard.html)
    descricao TEXT,
    materia_descricao VARCHAR(255),
    status VARCHAR(20) NOT NULL DEFAULT 'PENDENTE' CHECK (status IN ('PENDENTE', 'CONCLUIDA', 'CANCELADA')),
    data DATE DEFAULT CURRENT_DATE,
    datavencimento DATE,
    total_horas NUMERIC(10, 2),
    horas_ministradas NUMERIC(10, 2),

    -- Rastreamento
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

    -- Constraints
    CONSTRAINT pendencias_materia_avaliacao_unique UNIQUE NULLS NOT DISTINCT (materia_id, avaliacao_id),
    CONSTRAINT pendencias_pelo_menos_um_status CHECK (
        status_criacao_avaliacao IS NOT NULL OR
        status_plano_aula IS NOT NULL OR
        status_plano_ensino IS NOT NULL OR
        status_avaliacao IS NOT NULL OR
        status_gabarito IS NOT NULL OR
        status_revisao IS NOT NULL OR
        status_cadastro_sgn IS NOT NULL OR
        acompanhamento_pedagogico_sgn IS NOT NULL OR
        descricao IS NOT NULL
    )
);

-- Criar índices para otimização de consultas
CREATE INDEX IF NOT EXISTS idx_pendencias_materia_id ON pendencias(materia_id);
CREATE INDEX IF NOT EXISTS idx_pendencias_avaliacao_id ON pendencias(avaliacao_id);
CREATE INDEX IF NOT EXISTS idx_pendencias_status ON pendencias(status);
CREATE INDEX IF NOT EXISTS idx_pendencias_materia_status ON pendencias(materia_id, status);
CREATE INDEX IF NOT EXISTS idx_pendencias_avaliacao_status ON pendencias(avaliacao_id, status);
CREATE INDEX IF NOT EXISTS idx_pendencias_created_at ON pendencias(created_at);
CREATE INDEX IF NOT EXISTS idx_pendencias_datavencimento ON pendencias(datavencimento);

-- Criar função para atualizar updated_at automaticamente
CREATE OR REPLACE FUNCTION update_pendencias_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Criar trigger para atualizar updated_at
DROP TRIGGER IF EXISTS trigger_pendencias_updated_at ON pendencias;
CREATE TRIGGER trigger_pendencias_updated_at
BEFORE UPDATE ON pendencias
FOR EACH ROW
EXECUTE FUNCTION update_pendencias_updated_at();

-- =============================================================================
-- COMENTÁRIOS NA TABELA
-- =============================================================================

COMMENT ON TABLE pendencias IS 'Rastreamento completo de pendências: matérias, avaliações e tarefas gerais. Um registro por matéria/avaliação com pendências, + registros de tarefas manuais.';
COMMENT ON COLUMN pendencias.id IS 'Identificador único da pendência';
COMMENT ON COLUMN pendencias.materia_id IS 'Referência para a matéria (obrigatório)';
COMMENT ON COLUMN pendencias.avaliacao_id IS 'Referência para a avaliação (opcional, apenas se a pendência é de avaliação)';
COMMENT ON COLUMN pendencias.status_criacao_avaliacao IS 'Status de pendência: criação de avaliação na matéria';
COMMENT ON COLUMN pendencias.status_plano_aula IS 'Status de pendência: plano de aula';
COMMENT ON COLUMN pendencias.status_plano_ensino IS 'Status de pendência: plano de ensino';
COMMENT ON COLUMN pendencias.status_avaliacao IS 'Status de pendência: avaliação em si';
COMMENT ON COLUMN pendencias.status_gabarito IS 'Status de pendência: gabarito da avaliação';
COMMENT ON COLUMN pendencias.status_revisao IS 'Status de pendência: revisão da avaliação';
COMMENT ON COLUMN pendencias.status_cadastro_sgn IS 'Status de pendência: cadastro no SGN';
COMMENT ON COLUMN pendencias.acompanhamento_pedagogico_sgn IS 'Status de pendência: acompanhamento pedagógico SGN';
COMMENT ON COLUMN pendencias.descricao IS 'Descrição da pendência (para tarefas manuais)';
COMMENT ON COLUMN pendencias.materia_descricao IS 'Nome da matéria associada (cópia para busca/exibição)';
COMMENT ON COLUMN pendencias.status IS 'Status geral da pendência: PENDENTE, CONCLUIDA ou CANCELADA';
COMMENT ON COLUMN pendencias.data IS 'Data de criação/registro da pendência';
COMMENT ON COLUMN pendencias.datavencimento IS 'Data de vencimento da pendência';
COMMENT ON COLUMN pendencias.total_horas IS 'Total de horas planejadas (para tarefas)';
COMMENT ON COLUMN pendencias.horas_ministradas IS 'Horas já ministradas (para tarefas)';
COMMENT ON COLUMN pendencias.created_at IS 'Timestamp de criação do registro';
COMMENT ON COLUMN pendencias.updated_at IS 'Timestamp da última atualização';

-- =============================================================================
-- Exemplos de inserção (comentados)
-- =============================================================================

/*
-- Exemplo 1: Pendência de matéria com múltiplos status (automático)
INSERT INTO pendencias (
    materia_id,
    status_criacao_avaliacao,
    status_plano_aula,
    status
) VALUES (
    1,
    'PENDENTE',
    'PENDENTE',
    'PENDENTE'
);

-- Exemplo 2: Pendência de avaliação (automático)
INSERT INTO pendencias (
    materia_id,
    avaliacao_id,
    status_avaliacao,
    status_gabarito,
    status
) VALUES (
    1,
    10,
    'PENDENTE',
    'PENDENTE',
    'PENDENTE'
);

-- Exemplo 3: Tarefa manual de pendência (manual via formulário)
INSERT INTO pendencias (
    materia_id,
    descricao,
    materia_descricao,
    status,
    data,
    datavencimento,
    total_horas,
    horas_ministradas
) VALUES (
    1,
    'Preparar material didático para Aula 5',
    'Fundamentos de Programação',
    'PENDENTE',
    CURRENT_DATE,
    CURRENT_DATE + INTERVAL '7 days',
    4,
    0
);

-- Exemplo 4: Marcar pendência como concluída
UPDATE pendencias
SET status = 'CONCLUIDA'
WHERE id = 1;
*/
