

gastos numa casa

#receitas - TODO DINHEIRO QUE ENTRA EM CASA
  1 PESSOA QUE TRABALHA NA FAMILIA
  pagamento - industria de alimentos - R$ 3500,00	
  freelancer - Desenhista de auto retrato - R$ 1200,00
  total = R$4700,00

#despesa
  Aluguel/Moradia - 1800,00
  Alimentacao     - 1200,00
  Educação        - 300,00
  Lazer           - 300,00
  Saúde           - 300,00
  Investimentos   - 800,00
  
#Saldo Mensal
Receita - despesa =>0,00



  
  
  




