-- ============================================================================
-- CONSOLIDAÇÃO DE TODOS OS SCRIPTS SQL DO PROJETO
-- ============================================================================

-- ============================================================================
-- 1. BACKFILL: atribui id inteiro incremental a materiais sem id
-- Arquivo original: backfill-material-ids.sql
-- ============================================================================
DO $$
DECLARE
  max_id  INTEGER;
  counter INTEGER;
  cur     RECORD;
  i       INTEGER;
  j       INTEGER;
  aula    JSONB;
  mat     JSONB;
  new_mats    JSONB;
  new_aula    JSONB;
  new_materias JSONB;
BEGIN
  -- acha o maior id inteiro já existente em qualquer material
  SELECT COALESCE(MAX((m->>'id')::integer), 0) INTO max_id
  FROM curso c,
       jsonb_array_elements(c.materias) AS a,
       jsonb_array_elements(a->'materiais') AS m
  WHERE c.materias IS NOT NULL
    AND m->>'id' ~ '^\d+$';

  counter := max_id;

  FOR cur IN SELECT id, materias FROM curso WHERE materias IS NOT NULL LOOP
    new_materias := '[]'::jsonb;

    FOR i IN 0 .. jsonb_array_length(cur.materias) - 1 LOOP
      aula     := cur.materias -> i;
      new_mats := '[]'::jsonb;

      IF aula -> 'materiais' IS NOT NULL THEN
        FOR j IN 0 .. jsonb_array_length(aula -> 'materiais') - 1 LOOP
          mat := aula -> 'materiais' -> j;
          IF (mat->>'id') IS NULL OR (mat->>'id') = '' THEN
            counter  := counter + 1;
            mat      := mat || jsonb_build_object('id', counter);
          END IF;
          new_mats := new_mats || jsonb_build_array(mat);
        END LOOP;
        new_aula := jsonb_set(aula, '{materiais}', new_mats);
      ELSE
        new_aula := aula;
      END IF;

      new_materias := new_materias || jsonb_build_array(new_aula);
    END LOOP;

    UPDATE curso SET materias = new_materias WHERE id = cur.id;
  END LOOP;

  RAISE NOTICE 'Backfill concluido. Ultimo id atribuido: %', counter;
END $$;

-- ============================================================================
-- 2. TABELA DE UNIDADES (locais de realização dos cursos)
-- Arquivo original: supabase-unidade.sql
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.unidade (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  descricao text NOT NULL,
  cidade text,
  bairro text,
  endereco text
);

ALTER TABLE public.unidade ENABLE ROW LEVEL SECURITY;

CREATE POLICY "unidade_select" ON public.unidade
  FOR SELECT USING (true);

CREATE POLICY "unidade_insert" ON public.unidade
  FOR INSERT WITH CHECK (true);

CREATE POLICY "unidade_update" ON public.unidade
  FOR UPDATE USING (true);

CREATE POLICY "unidade_delete" ON public.unidade
  FOR DELETE USING (true);

COMMENT ON TABLE public.unidade IS 'Locais onde os cursos são realizados.';
COMMENT ON COLUMN public.unidade.descricao IS 'Nome da unidade.';
COMMENT ON COLUMN public.unidade.cidade IS 'Cidade da unidade.';
COMMENT ON COLUMN public.unidade.bairro IS 'Bairro da unidade.';
COMMENT ON COLUMN public.unidade.endereco IS 'Endereço completo da unidade.';

-- ============================================================================
-- 3. ADICIONA COLUNA DE UNIDADE NA TABELA CURSO
-- Arquivo original: supabase-curso-unidade.sql
-- ============================================================================

ALTER TABLE public.curso
  ADD COLUMN IF NOT EXISTS unidade text;

COMMENT ON COLUMN public.curso.unidade IS
  'Nome da unidade/local de realização do curso.';

-- ============================================================================
-- 4. PREVINE CURSOS DUPLICADOS NA MESMA UNIDADE
-- Arquivo original: supabase-curso-duplicar.sql
-- ============================================================================

CREATE UNIQUE INDEX IF NOT EXISTS idx_curso_nome_unidade_unique
  ON public.curso (lower(trim(nome_completo)), lower(trim(unidade)))
  WHERE unidade IS NOT NULL;

-- Para unidades nulas, permite duplicatas (trata como "sem unidade definida")
-- mas previne múltiplos cursos sem unidade com o mesmo nome.
CREATE UNIQUE INDEX IF NOT EXISTS idx_curso_nome_sem_unidade_unique
  ON public.curso (lower(trim(nome_completo)))
  WHERE unidade IS NULL;

COMMENT ON INDEX public.idx_curso_nome_unidade_unique IS
  'Impede cursos com mesmo nome na mesma unidade.';

COMMENT ON INDEX public.idx_curso_nome_sem_unidade_unique IS
  'Impede cursos com mesmo nome quando a unidade não está definida.';

-- ============================================================================
-- 5. TABELA DE AVALIAÇÕES
-- Arquivo original: supabase-avaliacoes.sql
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.avaliacao (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  materia_id bigint NOT NULL REFERENCES public.materia(id) ON DELETE CASCADE,
  numero integer NOT NULL CHECK (numero > 0),
  titulo text NOT NULL,
  data_aplicacao date NOT NULL,
  status text NOT NULL DEFAULT 'PENDENTE'
    CHECK (status IN ('PENDENTE', 'ANDAMENTO', 'CONCLUIDO', 'CANCELADO')),
  status_aplicacao text NOT NULL DEFAULT 'PENDENTE'
    CHECK (status_aplicacao IN ('PENDENTE', 'ANDAMENTO', 'CONCLUIDO', 'CANCELADO')),
  status_revisao text NOT NULL DEFAULT 'PENDENTE'
    CHECK (status_revisao IN ('PENDENTE', 'ANDAMENTO', 'CONCLUIDO', 'CANCELADO')),
  status_cadastro_sgn text NOT NULL DEFAULT 'PENDENTE'
    CHECK (status_cadastro_sgn IN ('PENDENTE', 'ANDAMENTO', 'CONCLUIDO', 'CANCELADO')),
  acompanhamento_pedagogico_sgn text NOT NULL DEFAULT 'PENDENTE'
    CHECK (acompanhamento_pedagogico_sgn IN ('PENDENTE', 'ANDAMENTO', 'CONCLUIDO', 'CANCELADO')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (materia_id, numero)
);

ALTER TABLE public.avaliacao
  ADD COLUMN IF NOT EXISTS status_aplicacao text NOT NULL DEFAULT 'PENDENTE';

ALTER TABLE public.avaliacao
  ADD COLUMN IF NOT EXISTS acompanhamento_pedagogico_sgn text NOT NULL DEFAULT 'PENDENTE';

ALTER TABLE public.materia
  ADD COLUMN IF NOT EXISTS status_criacao_avaliacao text NOT NULL DEFAULT 'PENDENTE'
    CHECK (status_criacao_avaliacao IN ('PENDENTE', 'ANDAMENTO', 'CONCLUIDO', 'CANCELADO'));

ALTER TABLE public.materia
  ADD COLUMN IF NOT EXISTS status_plano_aula text NOT NULL DEFAULT 'PENDENTE'
    CHECK (status_plano_aula IN ('PENDENTE', 'ANDAMENTO', 'CONCLUIDO', 'CANCELADO'));

ALTER TABLE public.materia
  ADD COLUMN IF NOT EXISTS status_plano_ensino text NOT NULL DEFAULT 'PENDENTE'
    CHECK (status_plano_ensino IN ('PENDENTE', 'ANDAMENTO', 'CONCLUIDO', 'CANCELADO'));

ALTER TABLE public.materia
  ADD COLUMN IF NOT EXISTS ensalado boolean NOT NULL DEFAULT false;

-- Preserva o estado mais crítico de cada matéria antes de remover as colunas antigas.
DO $$
DECLARE
  v_coluna text;
  v_destino text;
BEGIN
  FOR v_coluna, v_destino IN
    SELECT * FROM (VALUES
      ('status_criacao', 'status_criacao_avaliacao'),
      ('status_plano_aula', 'status_plano_aula'),
      ('status_plano_ensino', 'status_plano_ensino')
    ) AS campos(origem, destino)
  LOOP
    IF EXISTS (
      SELECT 1
        FROM information_schema.columns
       WHERE table_schema = 'public'
         AND table_name = 'avaliacao'
         AND column_name = v_coluna
    ) THEN
      EXECUTE FORMAT(
        'UPDATE public.materia m SET %I = CASE '
        || 'WHEN EXISTS (SELECT 1 FROM public.avaliacao a WHERE a.materia_id = m.id AND a.%I = ''PENDENTE'') THEN ''PENDENTE'' '
        || 'WHEN EXISTS (SELECT 1 FROM public.avaliacao a WHERE a.materia_id = m.id AND a.%I = ''ANDAMENTO'') THEN ''ANDAMENTO'' '
        || 'WHEN EXISTS (SELECT 1 FROM public.avaliacao a WHERE a.materia_id = m.id AND a.%I = ''CONCLUIDO'') THEN ''CONCLUIDO'' '
        || 'ELSE m.%I END',
        v_destino, v_coluna, v_coluna, v_coluna, v_destino
      );
    END IF;
  END LOOP;
END;
$$;

ALTER TABLE public.avaliacao DROP COLUMN IF EXISTS status_criacao;
ALTER TABLE public.avaliacao DROP COLUMN IF EXISTS status_plano_aula;
ALTER TABLE public.avaliacao DROP COLUMN IF EXISTS status_plano_ensino;

UPDATE public.avaliacao
SET acompanhamento_pedagogico_sgn = 'CONCLUIDO'
WHERE acompanhamento_pedagogico_sgn = 'SEM_ALUNOS';

ALTER TABLE public.avaliacao
  DROP CONSTRAINT IF EXISTS avaliacao_status_check,
  DROP CONSTRAINT IF EXISTS avaliacao_status_aplicacao_check,
  DROP CONSTRAINT IF EXISTS avaliacao_status_revisao_check,
  DROP CONSTRAINT IF EXISTS avaliacao_status_cadastro_sgn_check,
  DROP CONSTRAINT IF EXISTS avaliacao_acompanhamento_pedagogico_sgn_check;

ALTER TABLE public.avaliacao
  ADD CONSTRAINT avaliacao_status_check
    CHECK (status IN ('PENDENTE', 'ANDAMENTO', 'CONCLUIDO', 'CANCELADO')),
  ADD CONSTRAINT avaliacao_status_aplicacao_check
    CHECK (status_aplicacao IN ('PENDENTE', 'ANDAMENTO', 'CONCLUIDO', 'CANCELADO')),
  ADD CONSTRAINT avaliacao_status_revisao_check
    CHECK (status_revisao IN ('PENDENTE', 'ANDAMENTO', 'CONCLUIDO', 'CANCELADO')),
  ADD CONSTRAINT avaliacao_status_cadastro_sgn_check
    CHECK (status_cadastro_sgn IN ('PENDENTE', 'ANDAMENTO', 'CONCLUIDO', 'CANCELADO')),
  ADD CONSTRAINT avaliacao_acompanhamento_pedagogico_sgn_check
    CHECK (acompanhamento_pedagogico_sgn IN ('PENDENTE', 'ANDAMENTO', 'CONCLUIDO', 'CANCELADO'));

ALTER TABLE public.materia
  DROP CONSTRAINT IF EXISTS materia_status_criacao_avaliacao_check,
  DROP CONSTRAINT IF EXISTS materia_status_plano_aula_check,
  DROP CONSTRAINT IF EXISTS materia_status_plano_ensino_check;

ALTER TABLE public.materia
  ADD CONSTRAINT materia_status_criacao_avaliacao_check
    CHECK (status_criacao_avaliacao IN ('PENDENTE', 'ANDAMENTO', 'CONCLUIDO', 'CANCELADO')),
  ADD CONSTRAINT materia_status_plano_aula_check
    CHECK (status_plano_aula IN ('PENDENTE', 'ANDAMENTO', 'CONCLUIDO', 'CANCELADO')),
  ADD CONSTRAINT materia_status_plano_ensino_check
    CHECK (status_plano_ensino IN ('PENDENTE', 'ANDAMENTO', 'CONCLUIDO', 'CANCELADO'));

ALTER TABLE public.avaliacao ENABLE ROW LEVEL SECURITY;

GRANT SELECT, INSERT, UPDATE, DELETE ON public.avaliacao TO anon;
GRANT USAGE, SELECT ON SEQUENCE public.avaliacao_id_seq TO anon;

DROP POLICY IF EXISTS "avaliacao_select_anon" ON public.avaliacao;
CREATE POLICY "avaliacao_select_anon" ON public.avaliacao
  FOR SELECT TO anon USING (true);

DROP POLICY IF EXISTS "avaliacao_insert_anon" ON public.avaliacao;
CREATE POLICY "avaliacao_insert_anon" ON public.avaliacao
  FOR INSERT TO anon WITH CHECK (true);

DROP POLICY IF EXISTS "avaliacao_update_anon" ON public.avaliacao;
CREATE POLICY "avaliacao_update_anon" ON public.avaliacao
  FOR UPDATE TO anon USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "avaliacao_delete_anon" ON public.avaliacao;
CREATE POLICY "avaliacao_delete_anon" ON public.avaliacao
  FOR DELETE TO anon USING (true);

CREATE OR REPLACE FUNCTION public.garantir_avaliacoes_materia(p_materia_id bigint)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.avaliacao
    (materia_id, numero, titulo, data_aplicacao)
  VALUES
    (p_materia_id, 1, 'Avaliação 1', current_date),
    (p_materia_id, 2, 'Avaliação 2', current_date + 7)
  ON CONFLICT (materia_id, numero) DO NOTHING;
END;
$$;

REVOKE ALL ON FUNCTION public.garantir_avaliacoes_materia(bigint) FROM public;
GRANT EXECUTE ON FUNCTION public.garantir_avaliacoes_materia(bigint) TO anon;

CREATE OR REPLACE FUNCTION public.impedir_menos_duas_avaliacoes()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
  IF (SELECT COUNT(*) FROM public.avaliacao WHERE materia_id = old.materia_id) <= 2 THEN
    RAISE EXCEPTION 'Cada matéria deve possuir no mínimo duas avaliações.';
  END IF;
  RETURN old;
END;
$$;

DROP TRIGGER IF EXISTS avaliacao_minimo_duas ON public.avaliacao;
CREATE TRIGGER avaliacao_minimo_duas
BEFORE DELETE ON public.avaliacao
FOR EACH ROW EXECUTE FUNCTION public.impedir_menos_duas_avaliacoes();

-- ============================================================================
-- 6. TABELA DE PENDÊNCIAS (versão simples)
-- Arquivo original: TABELA_PENDENCIAS.sql
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.pendencias (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  descricao text NOT NULL,
  obs text,
  status text NOT NULL DEFAULT 'ABERTO'
    CHECK (status IN ('ANDAMENTO', 'ABERTO', 'CONCLUIDO', 'CANCELADO')),
  data date NOT NULL DEFAULT current_date
);

-- ============================================================================
-- 7. TABELA DE PENDÊNCIAS (versão CRUD completa)
-- Arquivo original: supabase-pendencias.sql
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.pendencias (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  data date NOT NULL DEFAULT current_date,
  datavencimento date,
  descricao text NOT NULL,
  status text NOT NULL DEFAULT 'PENDENTE'
    CHECK (status IN ('PENDENTE', 'ANDAMENTO', 'CONCLUIDO', 'CANCELADO')),
  materia_id text,
  materia_descricao text,
  materia_link text,
  total_horas integer,
  horas_ministradas integer,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.pendencias ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "pendencias_select_anon" ON public.pendencias;
CREATE POLICY "pendencias_select_anon" ON public.pendencias
  FOR SELECT TO anon USING (true);

DROP POLICY IF EXISTS "pendencias_insert_anon" ON public.pendencias;
CREATE POLICY "pendencias_insert_anon" ON public.pendencias
  FOR INSERT TO anon WITH CHECK (true);

DROP POLICY IF EXISTS "pendencias_update_anon" ON public.pendencias;
CREATE POLICY "pendencias_update_anon" ON public.pendencias
  FOR UPDATE TO anon USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "pendencias_delete_anon" ON public.pendencias;
CREATE POLICY "pendencias_delete_anon" ON public.pendencias
  FOR DELETE TO anon USING (true);

INSERT INTO public.pendencias
  (id, data, datavencimento, descricao, status, materia_id, materia_descricao, materia_link, total_horas, horas_ministradas)
VALUES
  (1, '2026-08-24', '2026-08-24', 'AVALIACAO CEPLAS', 'PENDENTE', '509636', 'Introdução a comunicação oral e escrita para o mundo do trabalho', 'CRIAR', 33, 22),
  (2, '2026-08-24', '2026-08-25', 'AVALIACAO AI PRESID. GETULIO - LANÇAR NOTAS SISTEMA', 'PENDENTE', '553990', 'Introdução a Tecnologia da Informação e Comunicação', 'CRIAR', 40, 36),
  (3, '2026-08-24', '2026-08-25', 'ATIVIDADE DE BANCO DE DADOS(Pegar com Daniel Baumann) - ACOMPANHAR A TURMA APENAS', 'PENDENTE', '446366', 'BANCO DE DADOS', 'CRIAR', 80, 76)
ON CONFLICT (id) DO NOTHING;

SELECT setval(
  pg_get_serial_sequence('public.pendencias', 'id'),
  GREATEST((SELECT COALESCE(MAX(id), 1) FROM public.pendencias), 1),
  true
);

-- ============================================================================
-- 8. CADASTRA MATÉRIAS DO MAIS TECH E VINCULA AO CURSO
-- Arquivo original: supabase-materias-mais-tech.sql
-- ============================================================================

ALTER TABLE public.materia
  ADD COLUMN IF NOT EXISTS ementa_caminho text;

ALTER TABLE public.materia
  ADD COLUMN IF NOT EXISTS apostila_caminho text;

ALTER TABLE public.materia
  ADD COLUMN IF NOT EXISTS status_criacao_avaliacao text NOT NULL DEFAULT 'PENDENTE'
    CHECK (status_criacao_avaliacao IN ('PENDENTE', 'ANDAMENTO', 'CONCLUIDO'));

ALTER TABLE public.materia
  ADD COLUMN IF NOT EXISTS status_plano_aula text NOT NULL DEFAULT 'PENDENTE'
    CHECK (status_plano_aula IN ('PENDENTE', 'ANDAMENTO', 'CONCLUIDO'));

ALTER TABLE public.materia
  ADD COLUMN IF NOT EXISTS status_plano_ensino text NOT NULL DEFAULT 'PENDENTE'
    CHECK (status_plano_ensino IN ('PENDENTE', 'ANDAMENTO', 'CONCLUIDO'));

ALTER TABLE public.materia
  ADD COLUMN IF NOT EXISTS ensalado boolean NOT NULL DEFAULT false;

DO $$
DECLARE
  v_curso_id bigint;
BEGIN
  SELECT id
    INTO v_curso_id
    FROM public.curso
   WHERE nome_completo ILIKE '%MAIS%TECH%'
   ORDER BY CASE
     WHEN UPPER(TRIM(nome_completo)) = 'RIO DO SUL MAIS TECH - SENAI' THEN 0
     ELSE 1
   END,
   id
   LIMIT 1;

  IF v_curso_id IS NULL THEN
    RAISE EXCEPTION 'Curso Rio do Sul Mais Tech não encontrado na tabela curso.';
  END IF;

  WITH materias_mais_tech(nome) AS (
    VALUES
      ('Competências Socioemocionais e Empreendedorismo'),
      ('Exploração de Carreiras Industriais e Tecnológicas'),
      ('Fundamentos da Tecnologia e Programação'),
      ('Introdução à Comunicação Oral e Escrita para o Mundo do Trabalho'),
      ('Noções de Eletricidade e Circuitos Básicos'),
      ('Oficinas de Impressão 3D e Robótica'),
      ('Reforço de Linguagens'),
      ('Reforço Matemática e Raciocínio Lógico')
  )
  INSERT INTO public.materia (descricao, ativo)
  SELECT mm.nome, 1
    FROM materias_mais_tech mm
   WHERE NOT EXISTS (
     SELECT 1
       FROM public.materia m
      WHERE LOWER(TRIM(m.descricao)) = LOWER(TRIM(mm.nome))
   );

  WITH materias_mais_tech(nome) AS (
    VALUES
      ('Competências Socioemocionais e Empreendedorismo'),
      ('Exploração de Carreiras Industriais e Tecnológicas'),
      ('Fundamentos da Tecnologia e Programação'),
      ('Introdução à Comunicação Oral e Escrita para o Mundo do Trabalho'),
      ('Noções de Eletricidade e Circuitos Básicos'),
      ('Oficinas de Impressão 3D e Robótica'),
      ('Reforço de Linguagens'),
      ('Reforço Matemática e Raciocínio Lógico')
  )
  INSERT INTO public.cursomateria (cursoid, materiaid)
  SELECT v_curso_id, m.id
    FROM materias_mais_tech mm
    JOIN public.materia m
      ON LOWER(TRIM(m.descricao)) = LOWER(TRIM(mm.nome))
   WHERE NOT EXISTS (
     SELECT 1
       FROM public.cursomateria cm
      WHERE cm.cursoid = v_curso_id
        AND cm.materiaid = m.id
   );

  UPDATE public.materia
     SET ementa_caminho = CASE LOWER(TRIM(descricao))
       WHEN LOWER('Competências Socioemocionais e Empreendedorismo') THEN 'FICHA-PRODUTO-MAIS-TECH/COMPETENCIAS_SOCIOEMOCIONAIS_E_EMPREENDEDORISMO/ementa_Competencias_Socioemocionais_Empreendedorismo.md'
       WHEN LOWER('Exploração de Carreiras Industriais e Tecnológicas') THEN 'FICHA-PRODUTO-MAIS-TECH/EXPLORACAO_CARREIRAS_INDUSTRIAIS_TECNOLOGICAS/ementa_Exploracao_Carreiras_Industriais_Tecnologicas.md'
       WHEN LOWER('Fundamentos da Tecnologia e Programação') THEN 'FICHA-PRODUTO-MAIS-TECH/FUNDAMENTOS_DA_TECNOLOGIA_E_PROGRAMACAO/ementa_Fundamentos_Tecnologia_Programacao.md'
       WHEN LOWER('Introdução à Comunicação Oral e Escrita para o Mundo do Trabalho') THEN 'FICHA-PRODUTO-MAIS-TECH/INTRODUCAO_COMUNICACAO_ORAL_ESCRITA/Ementa_Introducao_Comunicacao_Oral_Escrita.md'
       WHEN LOWER('Noções de Eletricidade e Circuitos Básicos') THEN 'FICHA-PRODUTO-MAIS-TECH/NOCOES_ELETRICIDADE_CIRCUITOS_BASICOS/Ementa_Nocoes_Eletricidade_Circuitos_Basicos.md'
       WHEN LOWER('Oficinas de Impressão 3D e Robótica') THEN 'FICHA-PRODUTO-MAIS-TECH/OFICINAS_IMPRESSAO_3D_ROBOTICA/Ementa_Oficinas_Impressao_3D_Robotica.md'
       WHEN LOWER('Reforço de Linguagens') THEN 'FICHA-PRODUTO-MAIS-TECH/REFORCO_LINGUAGENS/Ementa_Reforco_Linguagens.md'
       WHEN LOWER('Reforço Matemática e Raciocínio Lógico') THEN 'FICHA-PRODUTO-MAIS-TECH/REFORCO_MATEMATICA_E_RACIOCINIO_LOGICO/ementa_Reforco_Matematica_Raciocinio_Logico.md'
       ELSE ementa_caminho
     END
   WHERE LOWER(TRIM(descricao)) IN (
     LOWER('Competências Socioemocionais e Empreendedorismo'),
     LOWER('Exploração de Carreiras Industriais e Tecnológicas'),
     LOWER('Fundamentos da Tecnologia e Programação'),
     LOWER('Introdução à Comunicação Oral e Escrita para o Mundo do Trabalho'),
     LOWER('Noções de Eletricidade e Circuitos Básicos'),
     LOWER('Oficinas de Impressão 3D e Robótica'),
     LOWER('Reforço de Linguagens'),
     LOWER('Reforço Matemática e Raciocínio Lógico')
   );

  UPDATE public.materia
     SET apostila_caminho = CASE LOWER(TRIM(descricao))
       WHEN LOWER('Competências Socioemocionais e Empreendedorismo') THEN 'FICHA-PRODUTO-MAIS-TECH/COMPETENCIAS_SOCIOEMOCIONAIS_E_EMPREENDEDORISMO/Apostila_Competencias_Socioemocionais_Empreendedorismo.md'
       WHEN LOWER('Exploração de Carreiras Industriais e Tecnológicas') THEN 'FICHA-PRODUTO-MAIS-TECH/EXPLORACAO_CARREIRAS_INDUSTRIAIS_TECNOLOGICAS/Apostila_Exploracao_Carreiras_Industriais_Tecnologicas.md'
       WHEN LOWER('Fundamentos da Tecnologia e Programação') THEN 'FICHA-PRODUTO-MAIS-TECH/FUNDAMENTOS_DA_TECNOLOGIA_E_PROGRAMACAO/Apostila_Fundamentos_Tecnologia_Programacao.md'
       WHEN LOWER('Introdução à Comunicação Oral e Escrita para o Mundo do Trabalho') THEN 'FICHA-PRODUTO-MAIS-TECH/INTRODUCAO_COMUNICACAO_ORAL_ESCRITA/Apostila_Comunicacao_Oral_Escrita_33h.md'
       WHEN LOWER('Noções de Eletricidade e Circuitos Básicos') THEN 'FICHA-PRODUTO-MAIS-TECH/NOCOES_ELETRICIDADE_CIRCUITOS_BASICOS/Apostila_Nocoes_Eletricidade_Circuitos_Basicos.md'
       WHEN LOWER('Oficinas de Impressão 3D e Robótica') THEN 'FICHA-PRODUTO-MAIS-TECH/OFICINAS_IMPRESSAO_3D_ROBOTICA/Apostila_Oficinas_Impressao_3D_Robotica.md'
       WHEN LOWER('Reforço de Linguagens') THEN 'FICHA-PRODUTO-MAIS-TECH/REFORCO_LINGUAGENS/Apostila_Reforco_Linguagens.md'
       WHEN LOWER('Reforço Matemática e Raciocínio Lógico') THEN 'FICHA-PRODUTO-MAIS-TECH/REFORCO_MATEMATICA_E_RACIOCINIO_LOGICO/Apostila_Reforco_Matematica_Raciocinio_Logico.md'
       ELSE apostila_caminho
     END
   WHERE LOWER(TRIM(descricao)) IN (
     LOWER('Competências Socioemocionais e Empreendedorismo'),
     LOWER('Exploração de Carreiras Industriais e Tecnológicas'),
     LOWER('Fundamentos da Tecnologia e Programação'),
     LOWER('Introdução à Comunicação Oral e Escrita para o Mundo do Trabalho'),
     LOWER('Noções de Eletricidade e Circuitos Básicos'),
     LOWER('Oficinas de Impressão 3D e Robótica'),
     LOWER('Reforço de Linguagens'),
     LOWER('Reforço Matemática e Raciocínio Lógico')
   );
END;
$$;

-- ============================================================================
-- FIM DO ARQUIVO CONSOLIDADO
-- ============================================================================
