-- Estrutura das avaliações vinculadas às matérias.
-- Execute no SQL Editor do projeto Supabase usado pelo dashboard.

create table if not exists public.avaliacao (
  id bigint generated by default as identity primary key,
  materia_id bigint not null references public.materia(id) on delete cascade,
  numero integer not null check (numero > 0),
  titulo text not null,
  data_aplicacao date not null,
  status text not null default 'PENDENTE'
    check (status in ('PENDENTE', 'ANDAMENTO', 'CONCLUIDO', 'CANCELADO')),
  status_aplicacao text not null default 'PENDENTE'
    check (status_aplicacao in ('PENDENTE', 'CONCLUIDO', 'CANCELADO')),
  status_revisao text not null default 'PENDENTE'
    check (status_revisao in ('PENDENTE', 'ANDAMENTO', 'CONCLUIDO')),
  status_cadastro_sgn text not null default 'PENDENTE'
    check (status_cadastro_sgn in ('PENDENTE', 'ANDAMENTO', 'CONCLUIDO')),
  acompanhamento_pedagogico_sgn text not null default 'PENDENTE'
    check (acompanhamento_pedagogico_sgn in ('SEM_ALUNOS', 'PENDENTE', 'CONCLUIDO')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (materia_id, numero)
);

alter table public.avaliacao
  add column if not exists status_aplicacao text not null default 'PENDENTE';

alter table public.avaliacao
  add column if not exists acompanhamento_pedagogico_sgn text not null default 'PENDENTE';

alter table public.materia
  add column if not exists status_criacao_avaliacao text not null default 'PENDENTE'
    check (status_criacao_avaliacao in ('PENDENTE', 'ANDAMENTO', 'CONCLUIDO'));

alter table public.materia
  add column if not exists status_plano_aula text not null default 'PENDENTE'
    check (status_plano_aula in ('PENDENTE', 'ANDAMENTO', 'CONCLUIDO'));

alter table public.materia
  add column if not exists status_plano_ensino text not null default 'PENDENTE'
    check (status_plano_ensino in ('PENDENTE', 'ANDAMENTO', 'CONCLUIDO'));

alter table public.materia
  add column if not exists ensalado boolean not null default false;

-- Preserva o estado mais crítico de cada matéria antes de remover as colunas antigas.
do $$
declare
  v_coluna text;
  v_destino text;
begin
  for v_coluna, v_destino in
    select * from (values
      ('status_criacao', 'status_criacao_avaliacao'),
      ('status_plano_aula', 'status_plano_aula'),
      ('status_plano_ensino', 'status_plano_ensino')
    ) as campos(origem, destino)
  loop
    if exists (
      select 1
        from information_schema.columns
       where table_schema = 'public'
         and table_name = 'avaliacao'
         and column_name = v_coluna
    ) then
      execute format(
        'update public.materia m set %I = case '
        || 'when exists (select 1 from public.avaliacao a where a.materia_id = m.id and a.%I = ''PENDENTE'') then ''PENDENTE'' '
        || 'when exists (select 1 from public.avaliacao a where a.materia_id = m.id and a.%I = ''ANDAMENTO'') then ''ANDAMENTO'' '
        || 'when exists (select 1 from public.avaliacao a where a.materia_id = m.id and a.%I = ''CONCLUIDO'') then ''CONCLUIDO'' '
        || 'else m.%I end',
        v_destino, v_coluna, v_coluna, v_coluna, v_destino
      );
    end if;
  end loop;
end;
$$;

alter table public.avaliacao drop column if exists status_criacao;
alter table public.avaliacao drop column if exists status_plano_aula;
alter table public.avaliacao drop column if exists status_plano_ensino;

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'avaliacao_status_aplicacao_check'
  ) then
    alter table public.avaliacao
      add constraint avaliacao_status_aplicacao_check
      check (status_aplicacao in ('PENDENTE', 'CONCLUIDO', 'CANCELADO'));
  end if;
end;
$$;

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'avaliacao_acompanhamento_pedagogico_sgn_check'
  ) then
    alter table public.avaliacao
      add constraint avaliacao_acompanhamento_pedagogico_sgn_check
      check (acompanhamento_pedagogico_sgn in ('SEM_ALUNOS', 'PENDENTE', 'CONCLUIDO'));
  end if;
end;
$$;

alter table public.avaliacao enable row level security;

grant select, insert, update, delete on public.avaliacao to anon;
grant usage, select on sequence public.avaliacao_id_seq to anon;

drop policy if exists "avaliacao_select_anon" on public.avaliacao;
create policy "avaliacao_select_anon" on public.avaliacao
  for select to anon using (true);

drop policy if exists "avaliacao_insert_anon" on public.avaliacao;
create policy "avaliacao_insert_anon" on public.avaliacao
  for insert to anon with check (true);

drop policy if exists "avaliacao_update_anon" on public.avaliacao;
create policy "avaliacao_update_anon" on public.avaliacao
  for update to anon using (true) with check (true);

drop policy if exists "avaliacao_delete_anon" on public.avaliacao;
create policy "avaliacao_delete_anon" on public.avaliacao
  for delete to anon using (true);

create or replace function public.garantir_avaliacoes_materia(p_materia_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.avaliacao
    (materia_id, numero, titulo, data_aplicacao)
  values
    (p_materia_id, 1, 'Avaliação 1', current_date),
    (p_materia_id, 2, 'Avaliação 2', current_date + 7)
  on conflict (materia_id, numero) do nothing;
end;
$$;

revoke all on function public.garantir_avaliacoes_materia(bigint) from public;
grant execute on function public.garantir_avaliacoes_materia(bigint) to anon;

create or replace function public.impedir_menos_duas_avaliacoes()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if (select count(*) from public.avaliacao where materia_id = old.materia_id) <= 2 then
    raise exception 'Cada matéria deve possuir no mínimo duas avaliações.';
  end if;
  return old;
end;
$$;

drop trigger if exists avaliacao_minimo_duas on public.avaliacao;
create trigger avaliacao_minimo_duas
before delete on public.avaliacao
for each row execute function public.impedir_menos_duas_avaliacoes();
