-- Estrutura das avaliações vinculadas às matérias.
-- Execute no SQL Editor do projeto Supabase usado pelo dashboard.

create table if not exists public.avaliacao (
  id bigint generated by default as identity primary key,
  materia_id bigint not null references public.materia(id) on delete cascade,
  numero integer not null check (numero > 0),
  titulo text not null,
  data_aplicacao date not null,
  status text not null default 'PENDENTE'
    check (status in ('PENDENTE', 'ANDAMENTO', 'CONCLUIDO', 'CANCELADO')),
  status_criacao text not null default 'PENDENTE'
    check (status_criacao in ('PENDENTE', 'ANDAMENTO', 'CONCLUIDO')),
  status_revisao text not null default 'PENDENTE'
    check (status_revisao in ('PENDENTE', 'ANDAMENTO', 'CONCLUIDO')),
  status_cadastro_sgn text not null default 'PENDENTE'
    check (status_cadastro_sgn in ('PENDENTE', 'ANDAMENTO', 'CONCLUIDO')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (materia_id, numero)
);

alter table public.avaliacao enable row level security;

grant select, insert, update, delete on public.avaliacao to anon;
grant usage, select on sequence public.avaliacao_id_seq to anon;

drop policy if exists "avaliacao_select_anon" on public.avaliacao;
create policy "avaliacao_select_anon" on public.avaliacao
  for select to anon using (true);

drop policy if exists "avaliacao_insert_anon" on public.avaliacao;
create policy "avaliacao_insert_anon" on public.avaliacao
  for insert to anon with check (true);

drop policy if exists "avaliacao_update_anon" on public.avaliacao;
create policy "avaliacao_update_anon" on public.avaliacao
  for update to anon using (true) with check (true);

drop policy if exists "avaliacao_delete_anon" on public.avaliacao;
create policy "avaliacao_delete_anon" on public.avaliacao
  for delete to anon using (true);

create or replace function public.garantir_avaliacoes_materia(p_materia_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.avaliacao
    (materia_id, numero, titulo, data_aplicacao)
  values
    (p_materia_id, 1, 'Avaliação 1', current_date),
    (p_materia_id, 2, 'Avaliação 2', current_date + 7)
  on conflict (materia_id, numero) do nothing;
end;
$$;

revoke all on function public.garantir_avaliacoes_materia(bigint) from public;
grant execute on function public.garantir_avaliacoes_materia(bigint) to anon;

create or replace function public.impedir_menos_duas_avaliacoes()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if (select count(*) from public.avaliacao where materia_id = old.materia_id) <= 2 then
    raise exception 'Cada matéria deve possuir no mínimo duas avaliações.';
  end if;
  return old;
end;
$$;

drop trigger if exists avaliacao_minimo_duas on public.avaliacao;
create trigger avaliacao_minimo_duas
before delete on public.avaliacao
for each row execute function public.impedir_menos_duas_avaliacoes();
