-- Estrutura do CRUD "Minhas Pendências".
-- Execute no SQL Editor do projeto Supabase usado pelo dashboard.

create table if not exists public.pendencias (
  id bigint generated by default as identity primary key,
  data date not null default current_date,
  datavencimento date,
  descricao text not null,
  status text not null default 'PENDENTE'
    check (status in ('PENDENTE', 'ANDAMENTO', 'CONCLUIDO', 'CANCELADO')),
  materia_id text,
  materia_descricao text,
  materia_link text,
  total_horas integer,
  horas_ministradas integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.pendencias enable row level security;

drop policy if exists "pendencias_select_anon" on public.pendencias;
create policy "pendencias_select_anon" on public.pendencias
  for select to anon using (true);

drop policy if exists "pendencias_insert_anon" on public.pendencias;
create policy "pendencias_insert_anon" on public.pendencias
  for insert to anon with check (true);

drop policy if exists "pendencias_update_anon" on public.pendencias;
create policy "pendencias_update_anon" on public.pendencias
  for update to anon using (true) with check (true);

drop policy if exists "pendencias_delete_anon" on public.pendencias;
create policy "pendencias_delete_anon" on public.pendencias
  for delete to anon using (true);

insert into public.pendencias
  (id, data, datavencimento, descricao, status, materia_id, materia_descricao, materia_link, total_horas, horas_ministradas)
values
  (1, '2026-08-24', '2026-08-24', 'AVALIACAO CEPLAS', 'PENDENTE', '509636', 'Introdução a comunicação oral e escrita para o mundo do trabalho', 'CRIAR', 33, 22),
  (2, '2026-08-24', '2026-08-25', 'AVALIACAO AI PRESID. GETULIO - LANÇAR NOTAS SISTEMA', 'PENDENTE', '553990', 'Introdução a Tecnologia da Informação e Comunicação', 'CRIAR', 40, 36),
  (3, '2026-08-24', '2026-08-25', 'ATIVIDADE DE BANCO DE DADOS(Pegar com Daniel Baumann) - ACOMPANHAR A TURMA APENAS', 'PENDENTE', '446366', 'BANCO DE DADOS', 'CRIAR', 80, 76)
on conflict (id) do nothing;

select setval(
  pg_get_serial_sequence('public.pendencias', 'id'),
  greatest((select coalesce(max(id), 1) from public.pendencias), 1),
  true
);
