-- Tabela de pendências.
-- Execute este script no SQL Editor do projeto Supabase.

create table if not exists public.pendencias (
  id bigint generated by default as identity primary key,
  descricao text not null,
  obs text,
  status text not null default 'ABERTO'
    check (status in ('ANDAMENTO', 'ABERTO', 'CONCLUIDO', 'CANCELADO')),
  data date not null default current_date
);
